lib/student_list_web/router.ex
defmodule StudentListWeb.Router do
  use StudentListWeb, :router

  import StudentListWeb.UserAuth

  @content_security_policy Application.compile_env(:student_list, :content_security_policy)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StudentListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers,
      %{"content-security-policy" => @content_security_policy,
        "referrer-policy" => "strict-origin-when-cross-origin",
        "permissions-policy" => "camera=(), microphone=(), payment=(), geolocation=()"}
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StudentListWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", StudentListWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    forward "/sent_emails", Bamboo.SentEmailViewerPlug

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: StudentListWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", StudentListWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", StudentListWeb do
    # XXX - should put :put_layout false calls here to get the torch layout instead of the root_layout
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    get "/admin", BusController, :index
    resources "/members", MemberController
    resources "/buses", BusController
    resources "/classes", ClassController
    resources "/addresses", AddressController
    resources "/students", StudentController
    resources "/adults", AdultController
    resources "/entries", EntryController
    resources "/settings", SettingController
    get "/listings", ListingController, :index
    get "/listings/download", ListingController, :download
  end

  scope "/", StudentListWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/student_list/directory/listing.ex
defmodule StudentList.Directory.Listing do
  @moduledoc """
  Helper functions to format strings for display
  """

  @doc """
  Verifies that a string is not nil or composed just of whitespace
  """
  def not_empty(nil), do: false
  def not_empty(str) do
    length = str |> String.trim |> String.length
    0 != length
  end

  @doc """
  Pluralize a string
  """
  def pluralize(1, singular, _plural), do: "1 #{singular}"
  def pluralize(count, _singular, plural), do: "#{count} #{plural}"

  @doc """
  Format a name, handling `nil`
  """
  def format_name(nil), do: ""
  def format_name(str) do
    String.trim(str)
  end

  @doc """
  Format a telephone number
  """
  def format_phone(str) do
    numbers = str |> String.replace(~r/[^0-9]/, "") |> String.trim_leading("1")
    case String.length(numbers) do
      10 -> clean_phone(numbers)
      _ -> str
    end
  end

  defp clean_phone(numbers) do
    {area, rest} = String.split_at(numbers, 3)
    {prefix, suffix} = String.split_at(rest, 3)
    Enum.join([area, prefix, suffix], "-")
  end

  @doc """
  Format state name
  """
  def format_state(str) do
    state = String.replace(str, ~r/[^A-Za-z]/, "")
    case String.length(state) do
      2 -> String.upcase(state)
      _ -> str
    end
  end

  @doc """
  Format the city/state/zip line of the address
  """
  def format_city_address(city, state, zip) do
    {has_city, city} = fix_string(city)
    {has_state, state} = fix_string(state)
    state = format_state(state)
    {_has_zip, zip} = fix_string(zip)

    comma = if has_city && has_state do
      ", "
    else
      ""
    end

    "#{city}#{comma}#{state}  #{zip}"
  end

  # returns {string_has_content_boolean?, string_value}
  # ("" if has_content is false)
  defp fix_string(nil), do: {false, ""}
  defp fix_string(str) do
    str = String.trim(str)
    {0 != String.length(str), str}
  end
end

lib/student_list_web/controllers/listing_controller.ex
defmodule StudentListWeb.ListingController do
  use StudentListWeb, :controller

  alias StudentList.Directory
  alias StudentList.Directory.Formatter
  
  plug(:put_root_layout, {StudentListWeb.LayoutView, "torch.html"})
  plug(:put_layout, false)
  
  def index(conn, _params) do
    render(conn, "index.html", classes: Directory.get_listing())
  end

  def download(conn, _params) do
    {:ok, tmp_path} = Formatter.write()

    conn
    |> put_resp_content_type("application/rtf")
    |> put_resp_header("content-disposition",
                       "attachment; filename=\"directory.rtf\"")
    |> send_file(200, tmp_path)
  end
end

lib/student_list_web/views/listing_view.ex
defmodule StudentListWeb.ListingView do
  use StudentListWeb, :view

end

lib/student_list_web/templates/listing/index.html.eex
<% alias StudentList.Directory.Listing %>
<div class="directory">
  <h2>Student Directory</h2>
  <div><%= link "Download", to: Routes.listing_path(@conn, :download, %{}) %></div>
  <%= for class <- @classes do %>
    <div class="classroom">
      <div class="class_name">
        <h2 class="class_name"><%= class.name %> (<%= Listing.pluralize(length(class.students), "Student", "Students") %>)</h2>
        <h3 class="teacher_name"><%= class.teacher %></h3>
      </div>
      <div class="students">
        <%= for student <- class.students do %>
          <div class="student_name_bus">
            <h4 class="student_name"><%= Listing.format_name(student.last_name) %>, <%= Listing.format_name(student.first_name) %></h4>
            <%= if student.bus.should_display do %>
              <span class="bus"><%= student.bus.name %></span><br>
            <% end %>
            <br>
          </div>
          <%= for address <- student.addresses do %>
            <%= for parent <- address.adults do %>
              <div class="parent_name">
                <span><b><%= Listing.format_name(parent.first_name) %> <%= Listing.format_name(parent.last_name) %></b></span><br>
                <div class="parent_contact">
                  <%= if Listing.not_empty(parent.email) do %>
                    <span class="email"><%= String.trim(parent.email) %></span><br>
                  <% end %>
                  <%= if Listing.not_empty(parent.mobile_phone) do %>
                    <span class="phone">Cell: <%= Listing.format_phone(parent.mobile_phone) %></span><br>
                  <% end %>
                  <br>
                </div>
              </div>
            <% end %>
            <div class="parent_address">
              <%= if Listing.not_empty(address.address1) do %>
                <span class="address_street"><%= String.trim(address.address1) %></span><br>
              <% end %>
              <%= if Listing.not_empty(address.address2) do %>
                <span class="address_street2"><%= String.trim(address.address2) %></span><br>
              <% end %>
              <%= if Listing.not_empty(address.city) do %>
                <span class="address_city"><%= String.trim(address.city) %>,</span>
              <% end %>
              <%= if Listing.not_empty(address.state) do %>
                <span class="address_state"><%= Listing.format_state(address.state) %>  </span>
              <% end %>
              <%= if Listing.not_empty(address.zip) do %>
                <span class="address_zip"><%= String.trim(address.zip) %></span><br>
              <% end %>
              <%= if Listing.not_empty(address.phone) do %>
                <span class="home_phone">Home Phone: <%= Listing.format_phone(address.phone) %></span><br>
              <% end %>
            </div>
            <br>
          <% end %>
          <p class="notes"><%= student.notes %></p>
          <br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>