lib/student_list_web/router.ex
defmodule StudentListWeb.Router do
  use StudentListWeb, :router

  import StudentListWeb.UserAuth

  @content_security_policy Application.compile_env(:student_list, :content_security_policy)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {StudentListWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers,
      %{"content-security-policy" => @content_security_policy,
        "referrer-policy" => "strict-origin-when-cross-origin",
        "permissions-policy" => "camera=(), microphone=(), payment=(), geolocation=()"}
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StudentListWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", StudentListWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    forward "/sent_emails", Bamboo.SentEmailViewerPlug

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: StudentListWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", StudentListWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", StudentListWeb do
    # XXX - should put :put_layout false calls here to get the torch layout instead of the root_layout
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    get "/admin", BusController, :index
    resources "/members", MemberController
    resources "/buses", BusController
    resources "/classes", ClassController
    resources "/addresses", AddressController
    resources "/students", StudentController
    resources "/adults", AdultController
    resources "/entries", EntryController
    resources "/settings", SettingController
    get "/listings", ListingController, :index
    get "/listings/download", ListingController, :download
  end

  scope "/", StudentListWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/student_list_web/controllers/address_controller.ex
defmodule StudentListWeb.AddressController do
  use StudentListWeb, :controller

  alias StudentList.Directory
  alias StudentList.Directory.Address

  
  plug(:put_root_layout, {StudentListWeb.LayoutView, "torch.html"})
  plug(:put_layout, false)
  

  def index(conn, params) do
    case Directory.paginate_addresses(params) do
      {:ok, assigns} ->
        render(conn, "index.html", assigns)
      error ->
        conn
        |> put_flash(:error, "There was an error rendering Addresses. #{inspect(error)}")
        |> redirect(to: Routes.address_path(conn, :index))
    end
  end

  def new(conn, _params) do
    changeset = Directory.change_address(%Address{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"address" => address_params}) do
    case Directory.create_address(address_params) do
      {:ok, address} ->
        conn
        |> put_flash(:info, "Address created successfully.")
        |> redirect(to: Routes.address_path(conn, :show, address))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    address = Directory.get_address!(id)
    render(conn, "show.html", address: address)
  end

  def edit(conn, %{"id" => id}) do
    address = Directory.get_address!(id)
    changeset = Directory.change_address(address)
    render(conn, "edit.html", address: address, changeset: changeset)
  end

  def update(conn, %{"id" => id, "address" => address_params}) do
    address = Directory.get_address!(id)

    case Directory.update_address(address, address_params) do
      {:ok, address} ->
        conn
        |> put_flash(:info, "Address updated successfully.")
        |> redirect(to: Routes.address_path(conn, :show, address))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", address: address, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    address = Directory.get_address!(id)
    {:ok, _address} = Directory.delete_address(address)

    conn
    |> put_flash(:info, "Address deleted successfully.")
    |> redirect(to: Routes.address_path(conn, :index))
  end
end

lib/student_list_web/views/address_view.ex
defmodule StudentListWeb.AddressView do
  use StudentListWeb, :view

  import Torch.TableView
  import Torch.FilterView
end

lib/student_list_web/templates/address/edit.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.address_path(@conn, :index), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Edit Address</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.address_path(@conn, :update, @address)) %>
  </div>
</section>

lib/student_list_web/templates/address/form.html.eex
<%= form_for @changeset, @action, [multipart: true, id: "torch-form"], fn f -> %>
  <fieldset class="torch-panel">
    <legend>
      <span>Details</span>
    </legend>
    <%= if @changeset.action do %>
      <p class="torch-form-error">Oops, something went wrong! Please check the errors below.</p>
    <% end %>
  
    <div class="torch-form-group">
      <%= label f, :address1 %>
      <%= text_input f, :address1 %>
      <%= error_tag f, :address1 %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :address2 %>
      <%= text_input f, :address2 %>
      <%= error_tag f, :address2 %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :city %>
      <%= text_input f, :city %>
      <%= error_tag f, :city %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :state %>
      <%= text_input f, :state %>
      <%= error_tag f, :state %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :zip %>
      <%= text_input f, :zip %>
      <%= error_tag f, :zip %>
    </div>
  
    <div class="torch-form-group">
      <%= label f, :phone %>
      <%= text_input f, :phone %>
      <%= error_tag f, :phone %>
    </div>
  
    <div class="torch-submit-form">
      <%= submit "Submit", class: "torch-submit-button" %>
    </div>
  </fieldset>
<% end %>

lib/student_list_web/templates/address/index.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "New Address", to: Routes.address_path(@conn, :new) %>
  </div>
</section>
<section id="torch-index-content">
  <div class="torch-container">
    <section id="torch-filters">
      <h3>Find Addresses <%= if length(@addresses) > 0 do %> (<%= length(@addresses) %>)<% end %></h3>
      <%= form_tag @conn.request_path, method: :get, id: "torch-filters-form" do %>

          <div class="field">
            <label>Address1</label>
            <%= filter_select(:address, :address1, @conn.params) %>
            <%= filter_string_input(:address, :address1, @conn.params) %>
          </div>

          <div class="field">
            <label>Address2</label>
            <%= filter_select(:address, :address2, @conn.params) %>
            <%= filter_string_input(:address, :address2, @conn.params) %>
          </div>

          <div class="field">
            <label>City</label>
            <%= filter_select(:address, :city, @conn.params) %>
            <%= filter_string_input(:address, :city, @conn.params) %>
          </div>

          <div class="field">
            <label>State</label>
            <%= filter_select(:address, :state, @conn.params) %>
            <%= filter_string_input(:address, :state, @conn.params) %>
          </div>

          <div class="field">
            <label>Zip</label>
            <%= filter_select(:address, :zip, @conn.params) %>
            <%= filter_string_input(:address, :zip, @conn.params) %>
          </div>

          <div class="field">
            <label>Phone</label>
            <%= filter_select(:address, :phone, @conn.params) %>
            <%= filter_string_input(:address, :phone, @conn.params) %>
          </div>




        <button type="submit" class="torch-button">Search</button>
        <%= link "Clear Filters", to: Routes.address_path(@conn, :index) %>
      <% end %>

    </section>

    <section id="torch-table">
    <%= if length(@addresses) > 0 do %>
      <table>
        <thead>
          <tr>

              <th><%= table_link(@conn, "Address1", :address1) %></th>

              <th><%= table_link(@conn, "Address2", :address2) %></th>

              <th><%= table_link(@conn, "City", :city) %></th>

              <th><%= table_link(@conn, "State", :state) %></th>

              <th><%= table_link(@conn, "Zip", :zip) %></th>

              <th><%= table_link(@conn, "Phone", :phone) %></th>

            <th><span>Actions</span></th>
          </tr>
        </thead>
        <tbody>
          <%= for address <- @addresses do %>
            <tr>

                <td><%= address.address1 %></td>

                <td><%= address.address2 %></td>

                <td><%= address.city %></td>

                <td><%= address.state %></td>

                <td><%= address.zip %></td>

                <td><%= address.phone %></td>

              <td class="torch-actions">
                <span><%= link "Show", to: Routes.address_path(@conn, :show, address) %></span>
                <span><%= link "Edit", to: Routes.address_path(@conn, :edit, address) %></span>
                <span><%= link "Delete", to: Routes.address_path(@conn, :delete, address), method: :delete, data: [confirm: "Are you sure?"] %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render Torch.PaginationView, "_pagination.html", assigns %>
    <% else %>
      <p class="torch-no-data">No Addresses match your search.</p>
    <% end %>
    </section>
  </div>
</section>

lib/student_list_web/templates/address/new.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Cancel", to: Routes.address_path(@conn, :index), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>New Address</h3>
    </div>
    <%= render "form.html", Map.put(assigns, :action, Routes.address_path(@conn, :create)) %>
  </div>
</section>

lib/student_list_web/templates/address/show.html.eex
<section id="torch-toolbar">
  <div class="torch-container">
    <%= link "Edit", to: Routes.address_path(@conn, :edit, @address), class: "torch-button" %>
    <%= link "Back", to: Routes.address_path(@conn, :index), class: "torch-button" %>
  </div>
</section>

<section id="torch-header-and-content">
  <div class="torch-container">
    <div class="header">
      <h3>Address Details</h3>
    </div>
    <ul>
      
        <li>
          <div class="torch-show-label">Address1:</div>
          <div class="torch-show-data"><%= @address.address1 %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Address2:</div>
          <div class="torch-show-data"><%= @address.address2 %></div>
        </li>
      
        <li>
          <div class="torch-show-label">City:</div>
          <div class="torch-show-data"><%= @address.city %></div>
        </li>
      
        <li>
          <div class="torch-show-label">State:</div>
          <div class="torch-show-data"><%= @address.state %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Zip:</div>
          <div class="torch-show-data"><%= @address.zip %></div>
        </li>
      
        <li>
          <div class="torch-show-label">Phone:</div>
          <div class="torch-show-data"><%= @address.phone %></div>
        </li>
      
        <%= for student <- @address.students do %>
          <li>
            <div class="torch-show-label">Student:</div>
            <span class="torch-show-data"><%= link student.first_name, to: Routes.student_path(@conn, :show, student) %></span>
          </li>
        <% end %>

        <%= for adult <- @address.adults do %>
          <li>
            <div class="torch-show-label">Adult:</div>
            <span class="torch-show-data"><%= link adult.first_name, to: Routes.adult_path(@conn, :show, adult) %></span>
          </li>
        <% end %>
    </ul>
  </div>
</section>